/**
 * useMockData.ts
 * Central mock data layer for Traveloop.
 * Used as fallback when Supabase returns empty results or fails.
 * All demo content lives here — dashboard never feels empty.
 */

import type { Trip, Expense, PackingItem, TripNote, CommunityPost, NotificationItem } from '../lib/types'

// ─── MOCK USER ───────────────────────────────────────────
export const MOCK_USER_ID = 'mock-user-sanjay-001'

// ─── MOCK TRIPS ──────────────────────────────────────────
export const MOCK_TRIPS: Trip[] = [
  {
    id: 'mock-trip-001',
    user_id: MOCK_USER_ID,
    title: 'Goa Beach Escape',
    description: 'A relaxing week along the golden coastline of Goa. Sun, sand, seafood, and sunsets.',
    cover_image: null,
    start_date: '2025-06-10',
    end_date: '2025-06-17',
    visibility: 'private',
    status: 'active',
    total_budget: 18000,
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    trip_stops: [
      {
        id: 'mock-stop-001a',
        trip_id: 'mock-trip-001',
        city_name: 'North Goa',
        country: 'India',
        arrival_date: '2025-06-10',
        departure_date: '2025-06-13',
        order_index: 1,
        cover_image: null,
        notes: 'Stay near Calangute Beach — great access to nightlife & water sports',
        created_at: new Date().toISOString(),
      },
      {
        id: 'mock-stop-001b',
        trip_id: 'mock-trip-001',
        city_name: 'South Goa',
        country: 'India',
        arrival_date: '2025-06-13',
        departure_date: '2025-06-17',
        order_index: 2,
        cover_image: null,
        notes: 'Palolem Beach — quieter, more scenic, perfect for relaxation',
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'mock-trip-002',
    user_id: MOCK_USER_ID,
    title: 'Singapore & Bali Explorer',
    description: 'Modern Singapore followed by the spiritual tranquility of Ubud and Canggu in Bali.',
    cover_image: null,
    start_date: '2025-08-01',
    end_date: '2025-08-14',
    visibility: 'private',
    status: 'planning',
    total_budget: 85000,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    trip_stops: [
      {
        id: 'mock-stop-002a',
        trip_id: 'mock-trip-002',
        city_name: 'Singapore',
        country: 'Singapore',
        arrival_date: '2025-08-01',
        departure_date: '2025-08-05',
        order_index: 1,
        cover_image: null,
        notes: 'Marina Bay Sands, Sentosa, Gardens by the Bay',
        created_at: new Date().toISOString(),
      },
      {
        id: 'mock-stop-002b',
        trip_id: 'mock-trip-002',
        city_name: 'Bali',
        country: 'Indonesia',
        arrival_date: '2025-08-05',
        departure_date: '2025-08-14',
        order_index: 2,
        cover_image: null,
        notes: 'Ubud rice terraces, Canggu surf, Uluwatu temple',
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'mock-trip-003',
    user_id: MOCK_USER_ID,
    title: 'Dubai Luxury Weekend',
    description: 'Quick 4-day luxury escape to Dubai — Burj Khalifa, desert safari, gold souk.',
    cover_image: null,
    start_date: '2025-07-04',
    end_date: '2025-07-08',
    visibility: 'private',
    status: 'planning',
    total_budget: 45000,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    trip_stops: [
      {
        id: 'mock-stop-003a',
        trip_id: 'mock-trip-003',
        city_name: 'Dubai',
        country: 'UAE',
        arrival_date: '2025-07-04',
        departure_date: '2025-07-08',
        order_index: 1,
        cover_image: null,
        notes: 'Stay in Downtown Dubai — Burj Khalifa area',
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'mock-trip-004',
    user_id: MOCK_USER_ID,
    title: 'Ooty Weekend Ride',
    description: 'A refreshing getaway through the Nilgiri hills. Cool weather, tea estates, toy train.',
    cover_image: null,
    start_date: '2025-05-20',
    end_date: '2025-05-25',
    visibility: 'private',
    status: 'completed',
    total_budget: 12000,
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    trip_stops: [
      {
        id: 'mock-stop-004a',
        trip_id: 'mock-trip-004',
        city_name: 'Coimbatore',
        country: 'India',
        arrival_date: '2025-05-20',
        departure_date: '2025-05-22',
        order_index: 1,
        cover_image: null,
        notes: 'Base city, explore Marudhamalai temple',
        created_at: new Date().toISOString(),
      },
      {
        id: 'mock-stop-004b',
        trip_id: 'mock-trip-004',
        city_name: 'Ooty',
        country: 'India',
        arrival_date: '2025-05-22',
        departure_date: '2025-05-25',
        order_index: 2,
        cover_image: null,
        notes: 'Botanical gardens, Doddabetta peak, Rose garden',
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'mock-trip-005',
    user_id: MOCK_USER_ID,
    title: 'Chennai Business Visit',
    description: 'Work trip + weekend leisure — explore Marina beach, Kapaleeshwarar temple, street food.',
    cover_image: null,
    start_date: '2025-09-05',
    end_date: '2025-09-09',
    visibility: 'private',
    status: 'planning',
    total_budget: 8000,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    trip_stops: [
      {
        id: 'mock-stop-005a',
        trip_id: 'mock-trip-005',
        city_name: 'Chennai',
        country: 'India',
        arrival_date: '2025-09-05',
        departure_date: '2025-09-09',
        order_index: 1,
        cover_image: null,
        notes: 'Business meetings Mon-Wed, leisure Thu-Fri',
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'mock-trip-006',
    user_id: MOCK_USER_ID,
    title: 'Bangalore to Goa Road Trip',
    description: 'Epic road trip through the Western Ghats. Music, mountains, waterfalls, and the sea.',
    cover_image: null,
    start_date: '2025-09-12',
    end_date: '2025-09-20',
    visibility: 'public',
    status: 'planning',
    total_budget: 22000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    trip_stops: [
      {
        id: 'mock-stop-006a',
        trip_id: 'mock-trip-006',
        city_name: 'Bangalore',
        country: 'India',
        arrival_date: '2025-09-12',
        departure_date: '2025-09-13',
        order_index: 1,
        cover_image: null,
        notes: 'Start point — fuel up and start early morning',
        created_at: new Date().toISOString(),
      },
      {
        id: 'mock-stop-006b',
        trip_id: 'mock-trip-006',
        city_name: 'Hubli',
        country: 'India',
        arrival_date: '2025-09-13',
        departure_date: '2025-09-14',
        order_index: 2,
        cover_image: null,
        notes: 'Overnight stop, try the local biryani',
        created_at: new Date().toISOString(),
      },
      {
        id: 'mock-stop-006c',
        trip_id: 'mock-trip-006',
        city_name: 'Goa',
        country: 'India',
        arrival_date: '2025-09-14',
        departure_date: '2025-09-20',
        order_index: 3,
        cover_image: null,
        notes: 'Final destination — 6 nights at Vagator beach',
        created_at: new Date().toISOString(),
      },
    ],
  },
]

// ─── MOCK EXPENSES (for Goa trip) ────────────────────────
export const MOCK_EXPENSES: Expense[] = [
  { id: 'mock-exp-001', trip_id: 'mock-trip-001', type: 'flights',       amount: 5200,  description: 'IndiGo — CBE to GOI return',         date: '2025-05-01', created_at: new Date().toISOString() },
  { id: 'mock-exp-002', trip_id: 'mock-trip-001', type: 'accommodation', amount: 6400,  description: 'Airbnb near Baga Beach (4 nights)',   date: '2025-05-01', created_at: new Date().toISOString() },
  { id: 'mock-exp-003', trip_id: 'mock-trip-001', type: 'food',          amount: 1800,  description: 'Restaurants & cafes budget',          date: '2025-05-01', created_at: new Date().toISOString() },
  { id: 'mock-exp-004', trip_id: 'mock-trip-001', type: 'activities',    amount: 2500,  description: 'Water sports package (Baga)',         date: '2025-05-02', created_at: new Date().toISOString() },
  { id: 'mock-exp-005', trip_id: 'mock-trip-001', type: 'transport',     amount: 900,   description: 'Bike rental for 4 days',              date: '2025-05-02', created_at: new Date().toISOString() },
  { id: 'mock-exp-006', trip_id: 'mock-trip-001', type: 'shopping',      amount: 800,   description: 'Baga night market',                   date: '2025-05-03', created_at: new Date().toISOString() },
]

// ─── MOCK PACKING ITEMS ──────────────────────────────────
export const MOCK_PACKING_ITEMS: PackingItem[] = [
  { id: 'mock-pack-001', trip_id: 'mock-trip-001', item_name: 'Passport & ID',           category: 'documents',  is_packed: true,  created_at: new Date().toISOString() },
  { id: 'mock-pack-002', trip_id: 'mock-trip-001', item_name: 'Sunscreen SPF 50',        category: 'toiletries', is_packed: true,  created_at: new Date().toISOString() },
  { id: 'mock-pack-003', trip_id: 'mock-trip-001', item_name: 'Swim shorts x3',          category: 'clothing',   is_packed: true,  created_at: new Date().toISOString() },
  { id: 'mock-pack-004', trip_id: 'mock-trip-001', item_name: 'Sandals',                 category: 'clothing',   is_packed: false, created_at: new Date().toISOString() },
  { id: 'mock-pack-005', trip_id: 'mock-trip-001', item_name: 'GoPro + charger',         category: 'electronics',is_packed: false, created_at: new Date().toISOString() },
  { id: 'mock-pack-006', trip_id: 'mock-trip-001', item_name: 'Travel adapter',          category: 'electronics',is_packed: true,  created_at: new Date().toISOString() },
  { id: 'mock-pack-007', trip_id: 'mock-trip-001', item_name: 'Motion sickness tablets', category: 'medical',    is_packed: false, created_at: new Date().toISOString() },
  { id: 'mock-pack-008', trip_id: 'mock-trip-001', item_name: 'Reusable water bottle',   category: 'gear',       is_packed: true,  created_at: new Date().toISOString() },
]

// ─── MOCK TRIP NOTES ──────────────────────────────────────
export const MOCK_NOTES: TripNote[] = [
  {
    id: 'mock-note-001',
    trip_id: 'mock-trip-001',
    stop_id: 'mock-stop-001a',
    note: 'The sunset at Calangute was absolutely surreal — warm orange skies melting into the Arabian Sea. The water sports package was totally worth ₹2,500!',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'mock-note-002',
    trip_id: 'mock-trip-001',
    stop_id: 'mock-stop-001a',
    note: 'Picked up a beautiful handmade lamp at the Baga night market. The live music was incredible — a local band playing Konkani folk songs under string lights.',
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
]

// ─── MOCK COMMUNITY POSTS ────────────────────────────────
export const MOCK_COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: 'mock-post-001',
    user_id: MOCK_USER_ID,
    title: 'Best hidden beaches in North Goa 🏖️',
    content: 'After 3 trips to Goa, here are my top 5 secret beaches that most tourists miss...',
    tag: 'Goa',
    replies_count: 12,
    likes_count: 47,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    profiles: { full_name: 'Sanjay', avatar_url: null },
  },
  {
    id: 'mock-post-002',
    user_id: 'mock-user-002',
    title: 'Dubai on a budget — is it actually possible?',
    content: 'Flew on Air Arabia, stayed in Deira, skipped the malls. Full budget breakdown inside.',
    tag: 'Budget',
    replies_count: 8,
    likes_count: 31,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    profiles: { full_name: 'Mohammed Saif', avatar_url: null },
  },
  {
    id: 'mock-post-003',
    user_id: 'mock-user-003',
    title: 'Solo female travel in Bali — safety tips 2025',
    content: 'Just returned from 2 weeks solo in Bali. Here is everything you need to know.',
    tag: 'Safety',
    replies_count: 21,
    likes_count: 89,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    profiles: { full_name: 'Nithya Shree', avatar_url: null },
  },
  {
    id: 'mock-post-004',
    user_id: 'mock-user-004',
    title: 'Bangalore to Goa road trip — complete route guide',
    content: 'Did this in September. Sharing my full route, stays, pitstops and fuel costs.',
    tag: 'Road Trip',
    replies_count: 6,
    likes_count: 22,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    profiles: { full_name: 'Dhanu Shree', avatar_url: null },
  },
  {
    id: 'mock-post-005',
    user_id: MOCK_USER_ID,
    title: 'Packing light for a 2-week Asia trip ✈️',
    content: 'Carry-on only for 14 days across Singapore + Bali. Here is exactly what I packed.',
    tag: 'Packing',
    replies_count: 15,
    likes_count: 63,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    profiles: { full_name: 'Sanjay', avatar_url: null },
  },
]

// ─── MOCK NOTIFICATIONS ──────────────────────────────────
export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'mock-notif-001',
    icon: 'flight_takeoff',
    color: '#3B82F6',
    title: 'Goa trip is coming up!',
    body: 'Your Goa Beach Escape starts in 3 weeks — make sure your checklist is ready.',
    time: '2h ago',
    unread: true,
  },
  {
    id: 'mock-notif-002',
    icon: 'account_balance_wallet',
    color: '#10B981',
    title: 'Budget on track',
    body: 'You\'ve spent ₹17,600 of ₹18,000 budget for Goa. Consider reviewing shopping expenses.',
    time: '1d ago',
    unread: true,
  },
  {
    id: 'mock-notif-003',
    icon: 'checklist',
    color: '#F59E0B',
    title: 'Packing reminder',
    body: '3 items still unpacked for Goa Escape: Sandals, GoPro, Motion sickness tablets.',
    time: '2d ago',
    unread: false,
  },
  {
    id: 'mock-notif-004',
    icon: 'groups',
    color: '#8B5CF6',
    title: 'Nithya Shree replied to your post',
    body: 'Great tips! I\'d also add that night buses are surprisingly comfortable for South Goa.',
    time: '3d ago',
    unread: false,
  },
  {
    id: 'mock-notif-005',
    icon: 'local_activity',
    color: '#EF4444',
    title: 'New visa requirement for Bali',
    body: 'Indonesia updated visa-on-arrival rules for Indian passport holders. Check before you fly.',
    time: '5d ago',
    unread: false,
  },
]
